/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: zoubo@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1StorageSpec struct {
	Desc string `json:"desc,omitempty"`
	IsDefaultStorage bool `json:"isDefaultStorage,omitempty"`
	S3Config *V1alpha1BackupS3Config `json:"s3Config,omitempty"`
	S3Provider string `json:"s3Provider,omitempty"`
	Tenant string `json:"tenant"`
	VolumeSnapshotConfig *V1alpha1VolumeSnapshotConfig `json:"volumeSnapshotConfig,omitempty"`
	VolumeSnapshotProvider string `json:"volumeSnapshotProvider,omitempty"`
}
