/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: zoubo@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// NamespaceStatus is information about the current status of a Namespace.
type V1NamespaceStatus struct {
	// Represents the latest available observations of a namespace's current state.
	Conditions []V1NamespaceCondition `json:"conditions,omitempty"`
	// Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
	Phase string `json:"phase,omitempty"`
}
