/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1BackupPlanStatus struct {
	Conditions []V1alpha1Condition `json:"conditions,omitempty"`
	CurrentJobName string `json:"currentJobName,omitempty"`
	CurrentJobPhase string `json:"currentJobPhase,omitempty"`
	// errors
	Errors []V1alpha1Error `json:"errors,omitempty"`
	JobDetail map[string]string `json:"jobDetail,omitempty"`
	Phase string `json:"phase,omitempty"`
}
