/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: zoubo@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1RestorePlanSpec struct {
	BackupName string `json:"backupName"`
	DestClusterName string `json:"destClusterName"`
	ExcludeResources []string `json:"excludeResources,omitempty"`
	NamespaceMappings []string `json:"namespaceMappings,omitempty"`
	Tenant string `json:"tenant"`
}
