/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type YsapiError struct {
	// error code
	Code string `json:"code,omitempty"`
	// error message
	Message string `json:"message,omitempty"`
	// error that caused this error
	OrigError string `json:"origError,omitempty"`
	// http status code
	StatusCode int32 `json:"statusCode,omitempty"`
}
