/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1StorageClass struct {
	AccessModes []string `json:"accessModes,omitempty"`
	Default_ bool `json:"default,omitempty"`
	Name string `json:"name,omitempty"`
	Provisioner string `json:"provisioner,omitempty"`
}
