/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1BackupJobReport struct {
	EndTime string `json:"endTime,omitempty"`
	ExpiredTime string `json:"expiredTime,omitempty"`
	StartTime string `json:"startTime,omitempty"`
	SubmitTime string `json:"submitTime,omitempty"`
	TotalPVC int32 `json:"totalPVC,omitempty"`
}
