/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// NamespaceCondition contains details about state of namespace.
type V1NamespaceCondition struct {
	LastTransitionTime string `json:"lastTransitionTime,omitempty"`
	Message string `json:"message,omitempty"`
	Reason string `json:"reason,omitempty"`
	// Status of the condition, one of True, False, Unknown.
	Status string `json:"status"`
	// Type of namespace controller condition.
	Type_ string `json:"type"`
}
