/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1Error struct {
	// error code
	Code string `json:"code,omitempty"`
	// human readable message of this error
	Message string `json:"message,omitempty"`
	// parameters of this error
	Params []string `json:"params,omitempty"`
	// severity
	Severity string `json:"severity,omitempty"`
}
