/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1BackupS3Config struct {
	AccessKeyId string `json:"accessKeyId"`
	Bucket string `json:"bucket"`
	CredsSecretName string `json:"credsSecretName,omitempty"`
	Insecure bool `json:"insecure,omitempty"`
	Region string `json:"region,omitempty"`
	S3url string `json:"s3url"`
	SecretAccessKey string `json:"secretAccessKey"`
}
