/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1Condition struct {
	// last time we got an update on a given condition
	LastHeartbeatTime string `json:"lastHeartbeatTime"`
	// last time the condition transit from one status to another
	LastTransitionTime string `json:"lastTransitionTime"`
	// human-readable message indicating details about last transition
	Message string `json:"message,omitempty"`
	// one-word CamelCase reason for the condition's last transition
	Reason string `json:"reason,omitempty"`
	// status of the condition, one of True, False, Unknown
	Status string `json:"status"`
	// type of condition.
	Type_ string `json:"type"`
}
