/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1VolumeSnapshotClass struct {
	DeletionPolicy string `json:"deletionPolicy"`
	Driver string `json:"driver"`
	Name string `json:"name"`
}
