/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1RestoreJobSpec struct {
	Action string `json:"action,omitempty"`
	BackupJobName string `json:"backupJobName"`
	BackupJobRef *V1alpha1BackupJobSpec `json:"backupJobRef,omitempty"`
	Desc string `json:"desc,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	RestoreName string `json:"restoreName"`
	RestorePlanRef *V1alpha1RestorePlanSpec `json:"restorePlanRef,omitempty"`
	Tenant string `json:"tenant"`
}
