/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1BackupJobSpec struct {
	Action string `json:"action,omitempty"`
	BackupName string `json:"backupName"`
	BackupPlanRef *V1alpha1BackupPlanSpec `json:"backupPlanRef,omitempty"`
	Desc string `json:"desc,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Tenant string `json:"tenant"`
}
