/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1RestoreJobReport struct {
	EndTime string `json:"endTime,omitempty"`
	StartTime string `json:"startTime,omitempty"`
	TotalPVC int32 `json:"totalPVC,omitempty"`
}
