/*
 * Backup Service
 *
 * Backup Service OpenAPI
 *
 * API version: v0.0.0-master+$Format:%h$
 * Contact: shaofeng@jibudata.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1RestoreJobStatus struct {
	Conditions []V1alpha1Condition `json:"conditions,omitempty"`
	// errors
	Errors []V1alpha1Error `json:"errors,omitempty"`
	Phase string `json:"phase,omitempty"`
	Progress *V1alpha1RestoreJobProgress `json:"progress,omitempty"`
	Report *V1alpha1RestoreJobReport `json:"report,omitempty"`
}
