apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: jibudata-backup-saas
  name: backup-saas-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jibu-tenant-operator-leader-election-role
  namespace: backup-saas-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jibu-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jibu-tenant-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: jibu-tenant-operator-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backupjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restorejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restorejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - backupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - backupjobs/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - backupjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - backupplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - backupplans/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - backupplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - restorejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - restorejobs/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - restorejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - restoreplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - restoreplans/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - restoreplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - storages/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ys.jibudata.com
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - ys.jibudata.com
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jibu-tenant-operator-leader-election-rolebinding
  namespace: backup-saas-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jibu-tenant-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jibu-tenant-operator-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jibu-tenant-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jibu-tenant-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jibu-tenant-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jibu-tenant-operator-role
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: ea0d4d76.jibudata.com
kind: ConfigMap
metadata:
  name: jibu-tenant-operator-config
  namespace: backup-saas-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: jibudata-backup-saas
  name: jibu-tenant-operator-metrics-service
  namespace: backup-saas-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/part-of: jibudata-backup-saas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: jibudata-backup-saas
  name: jibu-tenant-operator
  namespace: backup-saas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: jibudata-backup-saas
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: jibudata-backup-saas
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: QIMING_OPERATOR_REGISTRY
          value: registry.cn-shanghai.aliyuncs.com/jibudata
        - name: QIMING_OPERATOR_VERSION
          value: main.3be4a0b
        - name: QIMING_CONTROLLER_VERSION
          value: main.1216ddf
        - name: VELERO_VERSION
          value: v1.7.0
        - name: VELERO_INSTALLER_VERSION
          value: main.3be4a0b
        - name: VELERO_PLUGINS
          value: registry.cn-shanghai.aliyuncs.com/jibudata/velero-plugin-for-aws:v1.3.0,registry.cn-shanghai.aliyuncs.com/jibudata/velero-plugin-for-csi:v0.2.0
        image: registry.cn-shanghai.aliyuncs.com/jibudata/tenant-operator:main.3d50226
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: jibu-tenant-operator
      terminationGracePeriodSeconds: 10
