apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: jibudata-backup-saas
  name: backup-saas-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jibu-tenant-operator-leader-election-role
  namespace: backup-saas-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jibu-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jibu-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jibu-tenant-operator-leader-election-rolebinding
  namespace: backup-saas-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jibu-tenant-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jibu-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qiming-operator-role
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jibu-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jibu-proxy-role
subjects:
- kind: ServiceAccount
  name: jibu-tenant-operator
  namespace: backup-saas-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: ea0d4d76.jibudata.com
kind: ConfigMap
metadata:
  name: jibu-tenant-operator-config
  namespace: backup-saas-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: jibudata-backup-saas
  name: jibu-tenant-operator-metrics-service
  namespace: backup-saas-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/part-of: jibudata-backup-saas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: jibudata-backup-saas
  name: jibu-baas-tenant-operator
  namespace: backup-saas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: jibudata-backup-saas
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: jibudata-backup-saas
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: QIMING_OPERATOR_REGISTRY
          value: jibutech
        - name: QIMING_OPERATOR_VERSION
          value: main.2dfc19b
        - name: QIMING_CONTROLLER_VERSION
          value: v1.0.7-backup
        - name: VELERO_VERSION
          value: v1.5.3
        - name: VELERO_INSTALLER_VERSION
          value: v0.0.2
        #image: registry.cn-shanghai.aliyuncs.com/jibudata/tenant-operator:v0.1.9-backup
        image: jibutech/tenant-operator:main.c1083a4
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: jibu-tenant-operator
      terminationGracePeriodSeconds: 10
